# GoReleaser configuration for SSH Secret Keeper

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: sshsk
    main: ./cmd/main.go
    binary: sshsk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/rzago/ssh-secret-keeper/internal/cmd.Version={{.Version}}'
      - -X 'github.com/rzago/ssh-secret-keeper/internal/cmd.BuildTime={{.Date}}'
      - -X 'github.com/rzago/ssh-secret-keeper/internal/cmd.GitHash={{.ShortCommit}}'

archives:
  - id: sshsk-archive
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - configs/config.example.yaml

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: rzago
    name: ssh-vault-keeper
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## SSH Secret Keeper {{ .Tag }}

    ### Changes
  footer: |
    **Full Changelog**: https://github.com/rzago/ssh-vault-keeper/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Installation

    Download the appropriate binary for your platform and architecture:

    ```bash
    # Linux amd64
    curl -L https://github.com/rzago/ssh-vault-keeper/releases/download/{{ .Tag }}/ssh-vault-keeper-{{ .Version }}-linux-amd64.tar.gz -o sshsk.tar.gz
    tar -xzf sshsk.tar.gz
    sudo mv sshsk /usr/local/bin/

    # macOS amd64
    curl -L https://github.com/rzago/ssh-vault-keeper/releases/download/{{ .Tag }}/ssh-vault-keeper-{{ .Version }}-darwin-amd64.tar.gz -o sshsk.tar.gz
    tar -xzf sshsk.tar.gz
    sudo mv sshsk /usr/local/bin/

    # Windows amd64
    curl -L https://github.com/rzago/ssh-vault-keeper/releases/download/{{ .Tag }}/ssh-vault-keeper-{{ .Version }}-windows-amd64.zip -o sshsk.zip
    unzip sshsk.zip
    # Move sshsk.exe to your PATH
    ```

    ### Container Images

    Container images are available at:
    - `ssh-secret-keeper:{{ .Version }}`
    - `ssh-secret-keeper:latest` (for stable releases)

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch
      - merge conflict
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Security updates'
      regexp: "^.*sec[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

# Snapshots for testing
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# Metadata for the release
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
