# SSH Secret Keeper Configuration Example
# Copy this file to ~/.ssh-secret-keeper/config.yaml and customize

version: "1.0"

# AUTHENTICATION REQUIREMENTS:
# 1. VAULT_ADDR environment variable is required (Vault server address)
# 2. Authentication via VAULT_TOKEN environment variable OR token file
#    - VAULT_TOKEN takes priority if both are set
#    - Token file path can be overridden with SSHSK_VAULT_TOKEN_FILE env var

# Storage provider configuration
storage:
  provider: "vault"  # Options: vault, onepassword (s3 coming soon)

  # Vault configuration (when provider: vault)
  vault:
    address: "http://localhost:8200"  # Your Vault server address (override with VAULT_ADDR env var)
    token_file: "~/.ssh-secret-keeper/token"  # Path to Vault token file
    mount_path: "ssh-backups"  # KV v2 mount path in Vault
    namespace: ""  # Vault namespace (Enterprise only)
    tls_skip_verify: false  # Skip TLS verification (not recommended for production)

  # 1Password configuration (when provider: onepassword) - Coming Soon!
  # onepassword:
  #   server_url: "http://localhost:8080"  # 1Password Connect server URL
  #   token: "${OP_CONNECT_TOKEN}"  # 1Password Connect token (use env var)
  #   vault_id: "your-vault-id"  # 1Password vault ID to store backups
  #   item_template: "ssh-backup"  # Template for backup items

  # S3 configuration (when provider: s3) - Coming Soon!
  # s3:
  #   endpoint: "s3.amazonaws.com"
  #   region: "us-west-2"
  #   bucket: "ssh-backups"
  #   access_key_id: "${AWS_ACCESS_KEY_ID}"
  #   secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  #   prefix: "ssh-secret-keeper"

# Legacy Vault configuration (for backward compatibility)
# This will be used if storage.provider is not set
vault:
  address: "http://localhost:8200"
  token_file: "~/.ssh-secret-keeper/token"
  mount_path: "ssh-backups"
  namespace: ""
  tls_skip_verify: false

  # NEW: Storage strategy configuration
  storage_strategy: "universal"    # Options: "universal", "user", "machine-user", "custom"
  backup_namespace: ""             # Optional namespace for universal strategy
  custom_prefix: ""                # Required for custom strategy

# Backup behavior settings
backup:
  ssh_dir: "~/.ssh"  # SSH directory to backup
  hostname_prefix: false  # Include hostname in Vault path (disabled by default with universal storage)
  retention_count: 10  # Number of backups to keep

  # NEW: Path normalization and cross-machine compatibility
  normalize_paths: true            # Enable cross-user compatibility
  cross_machine_restore: true      # Enable cross-machine restore

  # Files to include in backup (glob patterns)
  include_patterns:
    - "*.rsa"
    - "*.pem"
    - "*.pub"
    - "id_rsa*"
    - "config"
    - "known_hosts*"
    - "authorized_keys"
    - "*_rsa"
    - "*_rsa.pub"

  # Files to exclude from backup (glob patterns)
  exclude_patterns:
    - "*.tmp"
    - "*.bak"
    - "*.old"
    - "*.orig"

  # Predefined categories for SSH files
  categories:
    services:
      - "service1_rsa"
      - "service2_rsa"
      - "service3_rsa"
      - "service4_rsa"
      - "service5_rsa"
    personal:
      - "id_rsa"
      - "local_rsa"
    work:
      - "work_key1.rsa"
      - "work_key2.rsa"
    cloud:
      - "cloud_key1_rsa"
      - "*aws*"
      - "*gcp*"

# Security settings
security:
  algorithm: "AES-256-GCM"  # Encryption algorithm
  key_derivation: "PBKDF2"  # Key derivation function
  iterations: 100000  # PBKDF2 iterations
  per_file_encrypt: true  # Encrypt each file separately
  verify_integrity: true  # Verify MD5 checksums after decryption

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "console"  # console, json

# Key detection settings
detectors:
  enabled:
    - "rsa"
    - "pem"
    - "openssh"
    - "config"
    - "hosts"

  # Custom patterns file (optional)
  custom_patterns_file: ""

  # Service to category mapping
  service_mapping:
    github: "git_hosting"
    gitlab: "git_hosting"
    bitbucket: "git_hosting"
    argocd: "automation"
    jenkins: "automation"
    aws: "cloud"
    gcp: "cloud"
    azure: "cloud"

  # Purpose assignment rules (glob patterns)
  purpose_rules:
    "*work*": "work"
    "*corp*": "work"
    "*office*": "work"
    "*personal*": "personal"
    "*service*": "service"
    "*cloud*": "service"
